#!/bin/bash
#Recording
if [ $# -eq 0 ]
  then
    echo "No extension supplied. Defaulting to .mp4"
    extension=".mp4"
  else
    extension=$1
fi

cd
film_destination=~/Desktop
file_name="simulator_recording_$(date +'%F_%H-%M-%S')"
echo "Recording to $film_destination/$file_name$extension"
xcrun simctl io booted recordVideo $film_destination/$file_name$extension

#GIF
destination=~/Desktop/PR_GIFs
rm -rf $destination/pngs
mkdir $destination/pngs
rm -rf $destination/gifs
mkdir $destination/gifs

if [ ! -d $destination/Recordings ]; then
    mkdir -p $destination/Recordings;
fi

echo -e "\nMaking GIF..."

f=$film_destination/$file_name$extension
name=$file_name

echo $f > $destination/log
ffmpeg -i $f -r 10 $destination/pngs/$name%04d.png 2>$destination/log
sips -s format gif $destination/pngs/$name*.png --out $destination/gifs  > /dev/null 2>$destination/log
gifsicle --optimize=3 --resize-width=320 --delay=10 --loopcount $destination/gifs/$name*.gif > $destination/$name.gif
echo -e "\nFinished making GIF!"

#Uncomment if you would like your recordings to be moved into this folder instead
mv $f $destination/Recordings

rm -rf $destination/gifs
rm -rf $destination/pngs
