#!/bin/bash
#Recording
if [ $# -eq 0 ]
  then
    echo "No extension supplied. Defaulting to .mp4"
    extension=".mp4"
  else
    extension=$1
fi

cd
film_destination=~/Desktop
file_name="simulator_recording_$(date +'%F_%H-%M-%S')"
echo "Recording to $film_destination/$file_name$extension"
xcrun simctl io booted recordVideo $film_destination/$file_name$extension
