#!/bin/bash
# Initial checks
if [ $# -eq 0 ]
  then
    echo -e "No arguments found. Please indicate the filename. Usage: $(basename "$0") <filename> (without quotes, just the
    path)\n"
    exit 1
fi

if [ $# -gt 1 ];  then
    echo -e "Too many arguments. Usage: $(basename "$0") <filename> (without quotes; remove or escape whitespace if
    present)\n"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "$1 is not a valid filename. Check file exists, has no whitespace and uses the right extension"
    exit 1
fi

# File names and paths
destination=~/Desktop/PR_GIFs
rm -rf $destination/pngs
mkdir $destination/pngs
rm -rf $destination/gifs
mkdir $destination/gifs

if [ ! -d $destination/Recordings ]; then
    mkdir -p $destination/Recordings;
fi

f="$1"
echo $f > $destination/log
name=${f//\\/} # remove escape characters
name=${name// /_} # substitute whitespace
name=$(basename $name ".${name##*.}") # remove extension

# GIF
echo "Making GIF..."
echo "ffmpeg" > $destination/log
ffmpeg -i "$f" -r 10 $destination/pngs/$name%04d.png 2>$destination/log

echo "sips">$destination/log
sips -s format gif $destination/pngs/$name*.png --out $destination/gifs >/dev/null 2>$destination/log

gifsicle --optimize=3 --resize-width=320 --delay=10 --loopcount $destination/gifs/$name*.gif > $destination/$name.gif

echo -e "\nFinished making GIF. Find it at:\n$destination/$name.gif"

# Comment if you would like your recordings to not be moved
mv "$f" $destination/Recordings

rm -rf $destination/gifs
rm -rf $destination/pngs
